"""更新表结构

Revision ID: 929041fc80d7
Revises: d5ddf5ac4deb
Create Date: 2024-08-30 16:01:39.355003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929041fc80d7'
down_revision: Union[str, None] = 'd5ddf5ac4deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR USING role[1]")
    op.alter_column('roles', 'privileges',
               existing_type=sa.VARCHAR(),
               type_=sa.ARRAY(sa.Integer()),
                    postgresql_using="privileges::integer[]",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'privileges',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
